name: Automated Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if any; optional)
      - name: Install dependencies
        run: python -m pip install --upgrade pip

      # Step 4: Run Test 1
      - name: Run Test 1 - 10 Numbers
        run: |
          python find_lowest_number.py test_data/test1_input.txt output1.txt
          diff output1.txt test_data/test1_expected.txt

      # Step 5: Run Test 2
      - name: Run Test 2 - Single Number
        run: |
          python find_lowest_number.py test_data/test2_input.txt output2.txt
          diff output2.txt test_data/test2_expected.txt

      # Step 6: Run Test 3
      - name: Run Test 3 - Blank File
        run: |
          python find_lowest_number.py test_data/test3_input.txt output3.txt
          diff output3.txt test_data/test3_expected.txt

      # Step 7: Run Test with numbers.txt
      - name: Run Test with numbers.txt
        run: |
          python find_lowest_number.py test_data/numbers.txt output_numbers.txt
          diff output_numbers.txt test_data/numbers.txt
